name: mingw-stdlib-test

on:
  push:
    branches: [ "main" ]

jobs:
  mingw-stdlib-test:
    runs-on: windows-2019
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Run stdlib test
        run: go test -race sort
